version: "3"
services:
  app:
    container_name: test-portainer-${NODE_ENV}-v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${APP_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
